### ISSUE TITLE
How about reducing the incoming damage by wearing an armor or a helmet ? 

### ISSUE THREAD

**Issue by dreezyduh** [NullSystemWorks/mtadayz#29]

**Comment by 0xCiBeR** [comment]
Well we could combine this with a gas helmet that reduces infection as in original Arma2:DayZ http://imgur.com/4WkuzrK

**Comment by 1B0Y** [comment]
I actually like the idea. Fetches in some elements of the DayZ Stand-alone into play.

**Comment by 1B0Y** [comment]
Can anyone reference the responsible script which handles player damage? Thanks.

**Comment by mtadayz** [comment]
handlers/players/client/player_damage.lua.

**Comment by 0xCiBeR** [comment]
Any updates on this? @1B0Y

**Comment by 1B0Y** [comment]
Implemented in ed7aacc1f268e67fab1f07a005ef3846a9010df0, however I have no idea how the loot table works, so i've requested @mtadayz if he can add helmet and moto to the table.

If you're wearing either the helmet or moto helmet, you can't be headshotted at all. However - this will later be modified so that either after a couple of shots to the helmet itself will result in the helmet being destroyed, or if the player uses a bigger gun (such as a sniper) it'll just penetrate it.

**Comment by mtadayz** [comment]
I modified it a bit because your code was checking if the player has the helmet in his inventory, not if he has it equipped. Also, snipers will deal full damage.
