### ISSUE TITLE
Various bugs.

### ISSUE THREAD

**Issue by ghost** [NullSystemWorks/mtadayz#61]
Good night!

So I recently made a **MTA Server** so I could play **DayZ gamemode** with my friends. I installed this one and I came across some buggy things. Let me explain.

1º -> After **hours & hours** of playing I did not have to eat 1 single time. I checked _Admin Panel_ to see my stats and **Hunger & Thirst** were always **100%.**

2º -> **TIME!** everytime I start the server the time on the watch does not pass, obviously not making **the day/night cicle.**

3º -> **Weather...** Oh boy, how I hate this one. It is **always**, and I swear, **always** raining. This is just horrendous.. GOD..

4º -> GPS **does not fit the frame** & it also needs improving.. _Like see your buddys on gps._

5º -> **Zombie spawns..** I think it is not necessary to talk about this.. **G@ngb@ng€d by 836472349 zombies that spawned in my head.**

Take ya' oldie **Chester** and go out there killin' sum _zambeis_!
**IkT.**

**Comment by 1B0Y** [comment]
Thanks for the feedback. The weather sys has been a discussed matter and we're trying to determine why it's always raining. I'll be implementing an option to disable this tomorrow evening for the meantime.

**Comment by ghost** [comment]
@1B0Y No problem, just want to solve some things.. :+1:

**Comment by mtadayz** [comment]
1. Will look into it. It's a bit strange, though, because my hunger and thirst were decreasing just fine during my testing periods.
**EDIT:** Can confirm it decreases way too slow. Fixing that.
2. I'll check that.
3. Yeah, I noticed that too. Could be a bug, but I'm not entirely sure.
**EDIT:** It's not really a bug, just an oversight. When the weather is first initialized, it only selects from weather that is rainy. Gonna fix that.
4. The GPS is quite unpolished, true, and I wanted to implement blips for the group system, but never came around to do it.
5. I'm working on a new zombie system. Takes a while, though.

**Comment by ghost** [comment]
1 & 2 & 3 ->Let me know when you fix those things please. 
4 & 5 -> Go up to it, the GPS is an easy fix (I would just remove it xD).. And about the zombies.. good you're making that new system they are just random. :D 

Keep up good work m8! @mtadayz 

Take ya' oldie **Chester** and go out there killin' sum _zambeis_!
**IkT.**

**Comment by mtadayz** [comment]
Fixed 1 and 3, can't find a bug for 2, time's working normal for me.
