### ISSUE TITLE
More configurable stuff.

### ISSUE THREAD

**Issue by ghost** [NullSystemWorks/mtadayz#64]
Hey there developers. I would like to **suggest** one thing.
I think some slots are pretty stupid on some cars.. like, how can a **Barracks** only hold **50 items** (just like the **Patriot** or the **Sadler**)? And how can a **tent** only hold **100 items**? **10 weapons** and it is **full..**
What I would like to see is **customizable slots on cars & tents.**

Take ya' oldie **Chester** and go out there killin' sum _zambeis_!
**IkT.**

**Comment by mtadayz** [comment]
Err, you can customize the inventory slots. The corresponding table is in tables/table_vehicles.lua, called "vehicleAddonsInfo".

If you edit the slots, you'll have to respawn all vehicles (stop server, delete vehicle.db, delete vehicleManager by entering delaccount vehicleManager in the console, start server), because the new slots aren't carried over.
