### ISSUE TITLE
[SUGGESTION] Add chance of getting random low damage pistol on start.

### ISSUE THREAD

**Issue by Risusama** [NullSystemWorks/mtadayz#72]
Sorry, accidentally pressed enter on title. -.-

But now the title says it all, I think.
Or maybe it does not.

The random pistol should not have any ammo supplied with it. Only the gun itself.
I think this could make it a little easier to get started, would it not?

**Comment by mtadayz** [comment]
If memory serves, the original ArmA II DayZ mod had it, but they removed it after complaints of (re)spawned players spawnkilling each other. And not having any ammo for it kind of defeats the purpose, because most of the time, weapons spawn with their respective ammo (unless you are really unlucky). In short, I don't particularly like this suggestion, but since this is open source, feel free to add it for your own server/at your own leisure.

**Comment by 1B0Y** [comment]
Would make players scavenge for better weapons instead of having "brand new" ones as we currently do (I think). Seems ideal to balance the playing field out a little more. Would other weapons behave in the same way?

**Comment by Risusama** [comment]
@1B0Y 
> Would make players scavenge for better weapons instead of having "brand new" ones as we currently do (I think)

I'm not sure if I understood what you said. O.o

**Comment by mtadayz** [comment]
There's also another problem: weapons take up a lot of space (secondaries such as pistols 5 slots), so spawning along with one would simply make players drop the weapon in order to free up space, so that suggestion is kind of moot. I will close this, if no one minds.
