### ISSUE TITLE
Help [Inventory and Keys]

### ISSUE THREAD

**Issue by Alanaguilar** [NullSystemWorks/mtadayz#81]
Hello guys, I really appreciate your job, its amazing,
Can you guys help me?, I need to change the inventory to the classic dayz inventory, like 0.7.2 version, and I need to remove the keys for the sf base and area 69, If someone can help me,I would be very grateful. 

Thanks :)

**Comment by mtadayz** [comment]
The keycards can be removed/modified by editing objects.lua inside handlers/world/servers.

As for the inventory, good luck with that, because that's a mighty difficult feat, as you have to practically rewrite the entire inventory code, and we do not (nor do we want to) provide any in-depth guidelines.
