### ISSUE TITLE
White circle at crosshair

### ISSUE THREAD

**Issue by neves768** [NullSystemWorks/mtadayz#96]
White circle appearing at crosshair on specific weathers

Screenshot: http://prnt.sc/f5i2lj

**Comment by 0xCiBeR** [comment]
This is a shader related problem. Proably to do with the skyboxes.

**Comment by mtadayz** [comment]
I assume that's because the crosshair shader kind of overlays the skybox shader, producing that weird circle shape. It's an extremely old bug, though, dating back to the first time the realistic sky shader was put to use. Another possibility is that the internal GTA weather and its associated far clip distance values interferes with the shader Nothing we can really do about it, I'm afraid.
